version: '3.7'


services:
#  api:
#    build:
#      context: .
#    container_name: api
#    restart: always
#    ports:
#      - "8000:8000"
#    depends_on:
#      - redis
#      - db
#      - kafka
#      - kafka-ui
#      - zookeeper
#      - jaeger
#    networks:
#      jaeger-example:

  redis-stack-svc:
    image: redis/redis-stack-server:latest
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    environment:
      - REDIS_ARGS=--save 1200 32
    ports:
      - "6382:6379"
    container_name: redis_stack
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      jaeger-example:

  db:
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: sample
      TZ: GMT+3
    healthcheck:
      test: pg_isready -U sample -d sample
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      jaeger-example:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      jaeger-example:


  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
      - "9997:9997"
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9997
    depends_on:
      - zookeeper
    networks:
      jaeger-example:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      jaeger-example:

volumes:
  postgres_data:


networks:
  jaeger-example:
    name: jaeger-example
