"""add unique constr for username and email

Revision ID: 26f449d167af
Revises: 31c6baeb68e8
Create Date: 2023-07-11 16:17:50.974405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26f449d167af"
down_revision = "31c6baeb68e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    # ### end Alembic commands ###
